### PR TITLE
Create sv_se.lang

### PR DESCRIPTION
**Pull request by Regnander**

### CODE REVIEW

**Comment by Regnander** [comment]
Did I commit this to the correct branch?

**Comment by kierajreed** [comment]
Yes. I'll go ask ferreus if I can merge this, as it doesn't have any errors or anything.

**Comment by kierajreed** [comment]
Just capitalize the names as you see in en_en.lang. E.g. `Dynamic Oak` rather than `Dynamic oak`.

**Comment by Regnander** [comment]
> Just capitalize the names as you see in en_en.lang. E.g. `Dynamic Oak` rather than `Dynamic oak`.

The Swedish language doesn't use title case.

**Comment by Regnander** [comment]
>Yes. I'll go ask ferreus if I can merge this, as it doesn't have any errors or anything.

So I don't have to commit to the 1.13.x branch as well?

**Comment by kierajreed** [comment]
It'll get added to 1.13.x manually when work on 1.13 starts going.

**Pull request merged**
