### PR TITLE
Create it_it.json

### PR DESCRIPTION
**Pull request by Zano1999**

### CODE REVIEW

**Comment by Harleyoc1** [comment]
Thanks for the translations! Please change the base to 1.16.5 as it's currently 1.12.2 which does not use Json for its lang files.

**Comment by Harleyoc1** [comment]
Not as simple as that it turns out because you have committed the files to the 1.12.2 branch. Please re-commit to the 1.16.5 branch and re-open.

**Comment by Zano1999** [comment]
The translation is for the 1.18.2 version, do I reupload it on that branch?

**Comment by Harleyoc1** [comment]
If possible please open one for 1.16.5 as both versions are active. If you'd like one for 1.12.2 would also be appreciated but it's a bit of extra work because it uses different IDs and a different format.

**Pull request closed without merging**
