### PR TITLE
Config for disabling the Dirt Bucket's ability to place Dirt

### LINKED ISSUE #225: Dirt Bucket Right-click Config
**Request**
I would like to request a config option to disable the right-click functionality of the Dirt Bucket. I'm making a modpack where Iron is restricted until a certain stage, and the Dirt Bucket is made from a Clay Bucket + Dirt, so it's a bit game-breaking to have it turn into an empty bucket when used :P

I hope you'll consider it, and thank you for a great mod.

### PR DESCRIPTION
**Pull request by NielsPilgaard**
Added a config for disabling the Dirt Bucket's ability to place Dirt and subsequently return an empty bucket. Closes #225 

Warning: This is my first attempt at actual modding, so it's likely that I did not implement this correctly. 
I was unable to test it, because I couldn't find the version of HWYLA that gradle wanted.

### CODE REVIEW

**Comment by Asherslab** [comment]
@NillerMedDild btw the correct version of HWYLA can be found in my build gradle here: https://github.com/ferreusveritas/DynamicTrees/pull/258/files#diff-c197962302397baf3a4cc36463dce5ea

**Comment by NielsPilgaard** [comment]
Thanks for the help @Asherslab - This pull request has now been tested and works as intended.

**Comment by Asherslab** [comment]
No problem mate. Hopefully we'll both get our PRs merged. 
Seems like you've been waiting a while!

**Comment by NielsPilgaard** [comment]
Fingers crossed!

**Pull request merged**
