### PR TITLE
Adding maven gradle plugin back so that JFrog can properly detect what jars to release

### PR DESCRIPTION
**Pull request by marchermans**
This is the last one I promise. I tested it now against my fork properly.
Test release can be found under: https://ldtteam.jfrog.io/ldtteam/webapp/#/artifacts/browse/tree/General/mods/com/ferreusveritas/dynamictrees/DynamicTrees/1.12.2-0.7.7a-8

### CODE REVIEW

**Comment by marchermans** [comment]
Okey here we go. The build ran smoothly: https://teamcity.minecolonies.com/viewLog.html?buildId=21191&tab=buildResultsDiv&buildTypeId=FerreusVeritas_DynamicTrees_Main_Alpha_Release

And the relevant artifacts can be found on the maven now: https://ldtteam.jfrog.io/ldtteam/webapp/#/builds/Ferreus%20Veritas%20~2F%20Dynamic%20Trees%20~2F%20Main%20~2F%20Alpha%20~2F%20Release/0.7.7a-9/1541425060007

**Comment by ghost** [comment]
@OrionDevelopment Hey Marc,  It's been a while since you made this contribution to this repo but out of necessity I'm trying to update the maven content for DynamicTrees but I believe you are the one holding the credentials for the access.  At your convenience I'd like to get this moved under my control.  Thank you.

**Comment by marchermans** [comment]
@ferreusveritas I am not holding those credentials. Our buildsystem does.

If you have a new buildsystem, and maven repo. Feel free to tell me, then I can remove your mod from our buildsystem.
If you need to upload to your own maven, we can make that work as well.

Just tell me what you need.

**Comment by ghost** [comment]
If you were to remove it would we be able to submit it ourselves?  I'd hate to have to bother you every time we make a release.

**Comment by marchermans** [comment]
At the moment the system builds each of you commits and commits them to the maven.

Under normal operation you would figure out what you consider a release and we teach the CI/CD it
And it triggers a release for you.

That said, again if you have your own setup. Just send me a DM on Discord and I will scrap the one that we have now.
If you want to discuss how we can adapt the current system to something that works for you, then also send me a DM on discord.

I am not sure what your current way of making releases is, and how you want to integrate your own maven into this.
And until I know more, I am not sure i can do more then stop publishing to the ldtteam maven, but really I do not care. I can keep on publishing to it if you want to.

**Pull request merged**
