### PR TITLE
Add basic tree density configuration options

### PR DESCRIPTION
**Pull request by WolfieWaffle**
I have heard one other person in addition to myself say that it would be nice to be able to make the trees spawn less densely, these commits allow that. At the moment there is only separate groups for Forest Swamp and Sandy types but I can always change that. I think this would be a good configuration option for the mod.

### CODE REVIEW

**Comment by ghost** [comment]
I'm not opposed to the general idea of configurable densities but I'm not a fan of this specific  implementation.  I think it will become a runaway list of config options for every conceivable biome and/or biome "type".  I do not believe the config file would be the appropriate place to store this and would much rather see a json file(or whatever appropriate) that's loaded from a custom IBiomeDensityProvider provider that has a high priority.  The priority would be something like 9999 so it has priority over other providers.  If the DensityProviders were loaded from multiple files then the priority could conceivably be configurable as well.  At the moment we are in a feature freeze until release so we won't be adding anything like this for at least a couple weeks.

**Comment by WolfieWaffle** [comment]
Hm, that sounds a bit more advanced than I currently know how to do unless you want to explain it. I know JSON but not how this mod is really set up or how you would want me to load it and where etc. Maybe I could figure it out in time but as for now I won't be looking into it that deep for a while.

**Comment by ghost** [comment]
You don't need to.  I'm interested enough to do it on my own after this release is finished.  Thanks for the suggestion.

**Comment by WolfieWaffle** [comment]
No prob 👍

**Comment by ghost** [comment]
An issue has been put in the tracker for a new feature that can accommodate the needs addressed by this pull request.

**Pull request closed without merging**
